<?php
$fnum = 5;
$snum = 10;
$result = $fnum + $snum;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;
echo "Result " . $result;